<?php

namespace App\Http\Repositories;

use App\Models\Sympton;

class SymptonRepository extends BaseRepository implements RepositoryInterface
{
    protected $symptonModel;

    public function __construct(Sympton $sympton)
    {
        $this->symptonModel  = $sympton;
    }

    public function getAll()
    {
        return $this->symptonModel->all();
    }

    public function findById($id)
    {
        return $this->symptonModel->findOrFail($id);
    }

    public function save($obj)
    {
        return $this->symptonModel->save($obj);
    }

    public function delete($obj)
    {
        parent::delete($obj); // TODO: Change the autogenerated stub
    }
}

